name: Code Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: src/

jobs:
  checks:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.7.13"

      - name: Install dependencies
        run: uv sync --locked --all-extras --group test

      - name: Run Ruff
        run: uv run ruff check

      - name: Run Mypy
        run: uv run mypy .

      - name: Run Pytest
        run: uv run pytest -vx tests/
